name: Auto Merge of PRs for Users Data

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  automatic-pr-merge:
    name: Automatic PR Merge
    runs-on: ubuntu-latest
    steps:

      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v8.8
        id: changed_files
        with:
          files: _users/*

      - name: Commit files
        if: steps.changed_files.outputs.files_changed == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add _users/*
          git commit -m "Updated Achievements :rocket:"

      - name: Push changes
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
